// Auto-generated by tools/mkcard.py. Do not edit: re-run it.
//
// What the card file holds and in what order, for a build with CARDIMAGES on. The layout
// is set out in tools/mkcard.py; this only names the entries so the game can ask for one
// by name and check that the card it found was made by this build.

#pragma once
#include <stdint.h>

//the file the game looks for in the card's root
#define CARD_FILE_NAME "SOKOBAN.DAT"

//the same name as a FAT directory entry holds it: eight characters then three, no dot,
//which is the form CHSd's fat::find takes
#define CARD_FILE_83 "SOKOBAN DAT"

//every skin and picture name, hashed: a card made by another build has another stamp
#define CARD_STAMP 0xC0DC7510UL

//the sections of the container, by the name its table holds. Levels will be another one
#define CARD_SEC_IMAGES "IMGS"

//1 when any picture is kept as one colour a row, see FMT_ROWS. The game builds the
//code that draws one only then: a card without any is a game that need not carry it
#define CARD_HAS_ROWS 1

#define CARD_SKIN_COUNT 2
#define CARD_IMAGE_COUNT 7

//the skins, in the order the index holds them
enum CardSkin : uint8_t
{
	CARD_SKIN_DEFAULT = 0,
	CARD_SKIN_BLACK_WHITE = 1,
};

//what each skin is called on screen
#define CARD_SKIN_NAMES { "Default", "Black & white" }

//the pictures, in the order the index holds them within a skin
enum CardImage : uint8_t
{
	CARD_IMG_BACKGROUND = 0,
	CARD_IMG_BOX = 1,
	CARD_IMG_FLOOR = 2,
	CARD_IMG_PLAYER = 3,
	CARD_IMG_SPOT = 4,
	CARD_IMG_TITLESCREEN = 5,
	CARD_IMG_WALL = 6,
};
